### ISSUE TITLE
Bring List only displays in German

### ISSUE THREAD

**Issue by lrmansfi** [werthdavid/MMM-Bring#1]
Hi, thank-you for creating the Magic Mirror module. However, I have an English version installed on my phone but when my list displays on my Magic Mirror its displays in German. Is there a way to fix this?

**Comment by werthdavid** [comment]
Please try with the latest version and sorry for the inconvenience :)

**Comment by markPostema** [comment]
First of all, thank you for this module. But this issue is valid again. After I pulled the latest update, the productnames are in German.
