### ISSUE TITLE
module does not appear

### ISSUE THREAD

**Issue by tomtomlsg72** [werthdavid/MMM-Bring#10]
hello, i'm french so sorry for english :)
I followed the instructions but the module does not appear on my magic mirror. I installed the application on my phone and created an account, I saved the account info in the config.js but its does not work!

**Comment by werthdavid** [comment]
Hey,
Can you see some log-output? What region did you add the module in?

**Comment by tomtomlsg72** [comment]
Hi,
Nothing appears on the screen, not even an error, I installed the module as shown and add the code in my config.js.

{
		    module: "MMM-Bring",
		    position: "top_right",
		    config: {
		       email: "tomtomlsg72@gmail.com",
		       password: "azerty1234",
		       updateInterval: 15, // in Minutes
		       listName: "Maison", // optional
		       showListName: "true",
		       activeItemColor: "#EE524F",
		       latestItemColor: "#4FABA2",
		       showLatestItems: false,
		       maxItems: 0,
		       maxLatestItems: 0,
		       locale: "fr-FR"
		    }
		},

**Comment by werthdavid** [comment]
Your config works fine with my installation! Can you try a different position? Maybe there are too many other modules at that position so it disappears..

**Comment by tomtomlsg72** [comment]
Hi, I hadn't thought of that, but despite the change of position it wasn't working.
So I redid a new configuration and now it works perfectly.
There must have been something preventing it from working.
Thanks for your feedback, it's cool to have guys like you making things up and keeping an eye on the users.
Sorry for the english :)

**Comment by werthdavid** [comment]
You’re welcome!
