### ISSUE TITLE
I need to change the grid layout

### ISSUE THREAD

**Issue by Smiley-94** [werthdavid/MMM-Bring#14]
Hi, thank you for this awesome module,
would you please point me wich number into the css or js to change to make it print 8 items per line instead of 4? I guess it's just the width of the block but I cannot find it anywhere

**Comment by werthdavid** [comment]
Hey,
in the css/styles.css on the very bottom, you can see that depending on the module position the max-width is either 100% or 33vw (33% of the view-width).

Hope that helps?

**Comment by Smiley-94** [comment]
that was exactly what i was looking for, thank you
