### ISSUE TITLE
possible user error?

### ISSUE THREAD

**Issue by illbill4rill** [werthdavid/MMM-Bring#19]
Hello,

This Module seems really cool, unfortunately i am running into an issue, i get the error 
":8080/modules/MMM-Bring//MMM-Bring.js:99 Uncaught (in promise) TypeError: Cannot read property 'imageSrc' of undefined" 
I can post my config if you want, but it is exactly the same as the one in your readme except i put in my username and password and changed the name of the list to an existing one in my account.

Thank you so much for the assistance.

**Comment by werthdavid** [comment]
Hey, I'll take a look into that, I'm currently having issues as well.

**Comment by werthdavid** [comment]
Ok I think I've found the issue. Please update the module (by going into MM/modules/MMM-Bring and running git pull)

**Comment by illbill4rill** [comment]
Im still getting the same error, but now it is referencing line 154 instead of line 99

**Comment by werthdavid** [comment]
same error for recent items... I have no idea what kind of curious items you have in your list but it hope it works now 😄
