### ISSUE TITLE
Header ?

### ISSUE THREAD

**Issue by 2hdlockness** [werthdavid/MMM-Bring#22]
Hello
Would it be possible to add a header with the default configuration of MagicMirror when there is at least one item in the list and hide it when the list is empty?

**Comment by werthdavid** [comment]
Please test with latest version

**Comment by 2hdlockness** [comment]
Hello
This does not work and since the update other modules no longer work (MMM-News and MMM-TelegramBot). If I deactivate MMM-Bring everything is ok ...

**Comment by werthdavid** [comment]
Sorry for the inconvenience... Should work now (only if `showLatestItems` is false!)

**Comment by 2hdlockness** [comment]
It's ok, the other modules work together, but where can I define the name of the header?

**Comment by werthdavid** [comment]
I just implemented that the List-name (dropdown) is hidden if the list is empty. What kind of header would you like to display?

**Comment by 2hdlockness** [comment]
The default Magic Mirror header such as the agenda header for example.

**Comment by 2hdlockness** [comment]
Like this :
<a href="https://imgbb.com/"><img src="https://i.ibb.co/kDL2NzS/header.png" alt="header" border="0"></a>

**Comment by werthdavid** [comment]
can now be configured via `customHeader`

**Comment by 2hdlockness** [comment]
That's perfect, thank you very much !
One more little whim, can you add the number of items in the list in the header?
`headerElem.innerText = this.config.customTitle + ' (' + this.currentList.purchase.length + ')';`

**Comment by werthdavid** [comment]
✔️

**Comment by 2hdlockness** [comment]
In fact I have 2 little whims: Can you also add this function to allow you to display or hide the module via a 

         if (notification === 'HIDE_SHIPPING') {
              this.hide(1000, {lockString: "LOCKEDBYMODULE"});
            } else if (notification === 'SHOW_SHIPPING') {
              this.show(1000, {lockString: "LOCKEDBYMODULE"});
            }

**Comment by 2hdlockness** [comment]
The meter does not work ...

**Comment by werthdavid** [comment]
What meter?

**Comment by 2hdlockness** [comment]
Sorry google traduction...
I wanted to talk about the number of articles that are not displayed in the header with your modification:
line 96 `title.innerText = this.config.customTitle + " (" + (this.currentList.purchase || []).length + ")";`
It works fine with mine:
line 78 `headerElem.innerText = this.config.customTitle + ' (' + this.currentList.purchase.length + ')';`

**Comment by werthdavid** [comment]
Mixed something up there...

**Comment by 2hdlockness** [comment]
Super the number of elements is bein displayed in the header !!! Thank you.
However, could you move the Hide / Show function to the "notificationReceived" part instead of "socketNotificationReceived".
Because I am using a recipe that works with Google Assistant and that runs the following command: `notificationExec: {
        notification: "HIDE_SHIPPING",
      }`

**Comment by werthdavid** [comment]
✔️

**Comment by 2hdlockness** [comment]
Thank you, everything is perfect now! Congratulations on your work and your responsiveness.
