### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by quark777** [werthdavid/MMM-Bring#26]
Hello,

unfortunately no more data is displayed.
I have not made any changes and the rest of the MagicMirrors works fine.

Thank you very much in advance.

**Comment by shak4031** [comment]
Hello,

I am encountering same issue, no data.

Thank you

**Comment by daniel-san-fried** [comment]
Same here, just FYI. Api or something seems broken.

**Comment by evanhsu** [comment]
This is possibly the same as #27 and there's some more details in that issue
