### ISSUE TITLE
UNDEFINED in place of the name of the product

### ISSUE THREAD

**Issue by elmattt** [werthdavid/MMM-Bring#4]
Hi,
i have undefined in place of the name of the product , using fr-FR locales. not for all products, but for those i write myself.
![Capture d’écran 2019-10-20 à 23 27 25](https://user-images.githubusercontent.com/56804333/67166593-38c8c500-f391-11e9-877d-5c65e06e47fd.png)

**Comment by Smiley-94** [comment]
same problem in Italian locale..  it may be something involving the fact that the product is non existent and created by us... (I think it handles only the pre inserted elements)

**Comment by werthdavid** [comment]
You are right! I'll fix that

**Comment by werthdavid** [comment]
Sorry for the inconvenience... please pull the latest repo and try again!

**Comment by elmattt** [comment]
It works !!! Thanks 😋
