### ISSUE TITLE
Adding new items via input

### ISSUE THREAD

**Issue by lavolp3** [werthdavid/MMM-Bring#8]
I wonder if there is a possibility to put in new values via an input and submit button. I have it set up in my fork but you would need a virtual keyboard for that and that's where I'm currently lost.
Do you know of a solution for a virtual keyboard for a mirror module? # #

**Comment by werthdavid** [comment]
Hmmm not really. 
Its still useful for me and others. I have MM running on a Raspberry Pi and my old iPad is the display. VNC gives me a keyboard so I can profit right away ;-)

**Comment by lavolp3** [comment]
I am working on this in my [add-input branch](https://github.com/lavolp3/MMM-Bring/tree/add-input) and I am nearly finished.
I am working on a RPi based dashboard for the kitchen and this will be very helpful
